# Assignment Questions


## Section A: Data Structures & Control Structures

### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original list:", numbers)

# 1. Append - add an element to the end of the list
numbers.append(60)
print("After append(60):", numbers)

# 2. Extend - add multiple elements to the end
numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)

# 3. Insert - insert an element at a specific position
numbers.insert(2, 25)  # Insert 25 at index 2
print("After insert(2, 25):", numbers)

# 4. Remove - remove the first occurrence of a value
numbers.remove(40)
print("After remove(40):", numbers)

# 5. Pop - remove and return the last element (or specified index)
popped_item = numbers.pop()  # Removes last element
print("After pop():", numbers, " | Popped item:", popped_item)

# 6. Clear - remove all items from the list
numbers_copy = numbers.copy()  # Copy for further demonstration
numbers.clear()
print("After clear():", numbers)

# Restore the list for next operations
numbers = numbers_copy

# 7. Index - find the position of the first occurrence of a value
index_30 = numbers.index(30)
print("Index of 30:", index_30)

# 8. Count - count how many times a value appears
count_20 = numbers.count(20)
print("Count of 20:", count_20)

# 9. Sort - sort the list in ascending order
numbers.sort()
print("After sort():", numbers)

# 10. Reverse - reverse the elements of the list
numbers.reverse()
print("After reverse():", numbers)


Original list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]
After pop(): [10, 20, 25, 30, 50, 60, 70]  | Popped item: 80
After clear(): []
Index of 30: 3
Count of 20: 1
After sort(): [10, 20, 25, 30, 50, 60, 70]
After reverse(): [70, 60, 50, 30, 25, 20, 10]


### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [2]:

students = ("Alice", "Bob", "Charlie")

print("Original tuple:", students)

# Try to change the second name
students[1] = "David"  

Original tuple: ('Alice', 'Bob', 'Charlie')


TypeError: 'tuple' object does not support item assignment

#### Above Explanation:

In Python, tuples are immutable, meaning their elements cannot be changed, added, or removed after creation.

When we try to assign a new value to students[1], Python raises a TypeError because modifying tuple elements is not allowed.

### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [3]:
numbers = {1, 2, 3, 2, 4, 5, 3, 1}
print("Set of numbers:", numbers)


Set of numbers: {1, 2, 3, 4, 5}


#### Above Explanation:

1.Sets do not allow duplicate elements.

Even though we added 1, 2, and 3 multiple times, the set automatically removes the duplicates.

Each element in a set must be unique.

2.Sets are unordered collections.

### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [4]:
# Create a dictionary
person = {
    "name": "Alice",
    "age": 25,
    "city": "New York"
}

print("Original dictionary:", person)

# Update the age
person["age"] = 26

# Add a new key 'email'
person["email"] = "alice@example.com"

# Print the final dictionary
print("Updated dictionary:", person)


Original dictionary: {'name': 'Alice', 'age': 25, 'city': 'New York'}
Updated dictionary: {'name': 'Alice', 'age': 26, 'city': 'New York', 'email': 'alice@example.com'}


### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [5]:

age = int(input("Enter your age: "))

# Check eligibility
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote yet.")


Enter your age:  12


You are not eligible to vote yet.


### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [6]:

# Input: take marks as a variable
marks = int(input("Enter your marks: "))

# Check grade using conditions
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")


Enter your marks:  299


Grade: A


### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [7]:

# Input: take a number from the user
num = int(input("Enter a number: "))

# Check if the number is positive
if num > 0:
    print("The number is positive.")
    
    # Nested check: is it even?
    if num % 2 == 0:
        print("It is also even.")
    else:
        print("It is odd.")
        
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")


Enter a number:  31


The number is positive.
It is odd.


## Section B: Numpy

### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [8]:

import numpy as np

# 1. Create a scalar using np.array()
scalar = np.array(5)
print("Scalar:\n", scalar)

# 2. Create a 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:\n", array_1d)

# 3. Create a 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])
print("\n2D Array (2x3):\n", array_2d)


Scalar:
 5

1D Array:
 [1 2 3 4 5]

2D Array (2x3):
 [[10 20 30]
 [40 50 60]]


### 9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [9]:

import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))

# Print the array
print("4x4 Random Integer Array:\n", random_array)


4x4 Random Integer Array:
 [[85 96 94 89]
 [56  1 85 35]
 [89  8 45 61]
 [54 82 22 42]]


### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [10]:
# Import required libraries
import numpy as np
import pandas as pd

# Step 1: Create a 2D NumPy array of shape (3x3)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print("2D NumPy Array:\n", array_2d)

# Step 2: Convert the NumPy array into a Pandas DataFrame
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])

# Step 3: Print the DataFrame
print("\nPandas DataFrame with column names:\n", df)


2D NumPy Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Pandas DataFrame with column names:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


## Section C: Exploring Pandas


### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [14]:
# Import Pandas
import pandas as pd
import numpy as np

# Step 1: Create a small DataFrame manually with 10 rows
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ian', 'Jack'],
    'Age': [25, 30, 35, 40, 28, 33, 29, 31, 30, 25],
    'City': ['NY', 'LA', 'Chicago', 'NY', 'LA', 'Chicago', 'NY', 'LA', 'Chicago', 'NY'],
    'Salary': [50000, 60000, np.nan, 80000, 55000, np.nan, 70000, 65000, 60000, 50000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Step 2: Use .info() and .describe()
print("\nDataFrame Info:")
print(df.info())

print("\nDataFrame Description:")
print(df.describe())

# Step 3: Select 'Name' and 'City' columns
name_city = df[['Name', 'City']]
print("\nSelected Columns (Name and City):\n", name_city)

# Step 4: Drop 'City' column
df_dropped = df.drop(columns=['City'])
print("\nDataFrame after dropping 'City' column:\n", df_dropped)

# Step 5: Fill missing values in 'Salary' with mean
mean_salary = df['Salary'].mean()
df['Salary'].fillna(mean_salary, inplace=True)
print("\nDataFrame after filling missing Salary with mean:\n", df)

# Step 6: Remove any duplicate rows
df_no_duplicates = df.drop_duplicates()
print("\nDataFrame after removing duplicates:\n", df_no_duplicates)


Original DataFrame:
       Name  Age     City   Salary
0    Alice   25       NY  50000.0
1      Bob   30       LA  60000.0
2  Charlie   35  Chicago      NaN
3    David   40       NY  80000.0
4      Eva   28       LA  55000.0
5    Frank   33  Chicago      NaN
6    Grace   29       NY  70000.0
7    Helen   31       LA  65000.0
8      Ian   30  Chicago  60000.0
9     Jack   25       NY  50000.0

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

DataFrame Description:
             Age        Salary
count  10.000000      8.000000
mean   30.600000  61250.000000
std     4.550946  10264.362759
min    25.000000  50000.000000
25%    28.2500

C:\Users\am\AppData\Local\Temp\ipykernel_11732\120334451.py:33: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(mean_salary, inplace=True)
